// Lumo Dreams — Audio-to-Text sentence aligner using Gemini 1.5 Flash.
//
// Sends the existing narration MP3s along with their spoken text to Gemini,
// requesting precise sentence-level start and end timestamps.
// Updates public/audio/*.json files on disk with exact alignments.
//
// Usage (Windows PowerShell):
//   $env:GEMINI_API_KEY="..."
//   node scripts/align-timings.mjs

import { readFile, writeFile } from "node:fs/promises";
import { existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const AUDIO_DIR = join(__dirname, "..", "public", "audio");
const API_KEY = process.env.GEMINI_API_KEY;
const MODEL = "gemini-3.1-pro-preview";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function alignTrack(filename) {
  const jsonPath = join(AUDIO_DIR, filename);
  const trackId = filename.replace(".json", "");
  const mp3Path = join(AUDIO_DIR, `${trackId}.mp3`);

  if (!existsSync(mp3Path)) {
    console.log(`  — Skip ${trackId} (no corresponding MP3 found)`);
    return;
  }

  console.log(`▶ Aligning timings for: ${trackId} …`);
  
  // Read target text and structured metadata
  const jsonData = JSON.parse(await readFile(jsonPath, "utf8"));
  const sentences = jsonData.words.map(item => item.w);
  const chapterText = sentences.join("\n");

  // Read MP3 bytes and encode to base64
  const mp3Buffer = await readFile(mp3Path);
  const base64Audio = mp3Buffer.toString("base64");

  const promptText = `
You are a highly precise audio-to-text forced alignment tool.
I have provided an audio recording (MP3 format) of a voice narrator reading a story, alongside the exact list of sentences spoken in it.

IMPORTANT GUIDELINES FOR ACCURATE ALIGNMENT:
1. The audio file contains natural pauses, breaths, sighs, and gasps (which were generated by tags like [sigh], [breath], or [gasp] in the narrator's script).
2. You MUST listen carefully to the audio and locate these sighs, gasps, and silence intervals.
3. The start time ("s") of each sentence must align precisely with the first spoken phoneme of the first word in that sentence.
4. The end time ("e") of each sentence must align precisely with the final spoken phoneme of the last word in that sentence.
5. Do NOT include silences, deep breaths, gasps, or sighs that occur *between* sentences in the sentence duration. There should be a gap (where end time of sentence N is less than start time of sentence N+1) representing the duration of the silence, sigh, or gasp.
6. Return timestamps with 3-decimal millisecond precision (e.g. 14.325).
7. DO NOT start a sentence late. The start time ("s") must be placed at the very first millisecond that the first syllable of the sentence begins. It is better to start slightly early (by 50-100ms) than to start late.
8. Verify that the start time ("s") of the sentence 'Each morning she watched the humans dress...' is positioned precisely when the narrator begins speaking the word 'Each' (around 79.8 to 80.3 seconds in Chapter 1).

Here is the exact list of sentences spoken, in sequential order:
${sentences.map((s, idx) => `${idx + 1}. "${s}"`).join("\n")}

Respond ONLY with a valid JSON array of objects in the exact order of the sentences:
[
  {
    "w": "The exact sentence text from the list",
    "s": start_time_in_seconds,
    "e": end_time_in_seconds
  }
]
`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`;
  const body = {
    contents: [
      {
        parts: [
          {
            inlineData: {
              mimeType: "audio/mp3",
              data: base64Audio
            }
          },
          {
            text: promptText
          }
        ]
      }
    ]
  };

  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json", "x-goog-api-key": API_KEY },
    body: JSON.stringify(body)
  });

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Gemini API Error (${res.status}): ${errorText}`);
  }

  const result = await res.json();
  const rawText = result?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!rawText) {
    throw new Error("Empty response content from Gemini API.");
  }

  let cleanText = rawText.trim();
  if (cleanText.startsWith("```json")) {
    cleanText = cleanText.substring(7);
  } else if (cleanText.startsWith("```")) {
    cleanText = cleanText.substring(3);
  }
  if (cleanText.endsWith("```")) {
    cleanText = cleanText.substring(0, cleanText.length - 3);
  }
  cleanText = cleanText.trim();

  const alignment = JSON.parse(cleanText);
  if (!Array.isArray(alignment) || alignment.length === 0) {
    throw new Error("Invalid response format: expected a non-empty JSON array.");
  }

  // Soft verification: check if count matches
  if (alignment.length !== sentences.length) {
    console.warn(`  ⚠️ Warning: Sentences count mismatch. Expected ${sentences.length}, got ${alignment.length}. Matching closest indices.`);
  }

  // Update words array in JSON structure
  jsonData.words = alignment.map((item, idx) => {
    // Keep target text from our original chapters definition to preserve spelling
    const originalText = sentences[idx] || item.w;
    return {
      w: originalText,
      s: typeof item.s === "number" ? +item.s.toFixed(3) : 0,
      e: typeof item.e === "number" ? +item.e.toFixed(3) : 0
    };
  });

  await writeFile(jsonPath, JSON.stringify(jsonData, null, 2), "utf8");
  console.log(`  ✓ Timings aligned successfully (${jsonData.words.length} items saved).\n`);
}

async function main() {
  if (!API_KEY) {
    console.error("Error: GEMINI_API_KEY environment variable is not defined.");
    process.exit(1);
  }

  console.log("Analyzing audio assets directory …");
  const files = readdirSync(AUDIO_DIR).filter(
    (f) => f.endsWith(".json") && f !== "manifest.json"
  );

  console.log(`Found ${files.length} tracks to align.\n`);

  for (const file of files) {
    try {
      await alignTrack(file);
      // Brief sleep between calls to avoid API rate limit triggers
      await sleep(1500);
    } catch (err) {
      console.error(`  ✗ Error aligning ${file}: ${err.message}\n`);
    }
  }

  console.log("🎉 All audio tracks aligned successfully!");
}

main().catch(console.error);
